version: "3.8"
services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment: 
      - ACCEPT_EULA=Y 
      - MSSQL_SA_PASSWORD=yourStrong!Password
    ports:
      - 1433:1433
    volumes:
      - ./db-files:/var/opt/mssql/backup
#      - ./db-data:/var/opt/mssql

#volumes:
#  db-data:
