apiVersion: v1
kind: Service
metadata:
  name: service-mssql
spec:
  type: NodePort
  selector:
    app: mssql
  ports:
    - port: 1433
      targetPort: 1433
      nodePort: 30007
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-pv-claim
  labels:
    app: mssql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
