apiVersion: v1
kind: Service
metadata:
  name: service-mssql
spec:
  type: NodePort
  selector:
    app: mssql
  ports:
    - port: 1433
      targetPort: 1433
      nodePort: 30007
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-pv-claim
  labels:
    app: mssql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql
spec:
  selector:
    matchLabels:
      app: mssql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mssql
    spec:
      containers:
      - image: mcr.microsoft.com/mssql/server:2022-latest
        name: mssql
        env:
          # Use secret in real usage
        - name: MSSQL_SA_PASSWORD
          value: yourStrong!Password
        - name: ACCEPT_EULA
          value: 'Y'
        ports:
        - containerPort: 1433
          name: mssql
        volumeMounts:
        - name: mssql-persistent-storage
          mountPath: /var/opt/mssql
      volumes:
      - name: mssql-persistent-storage
        persistentVolumeClaim:
          claimName: mssq-pv-claim
